package Model_view;

import javax.swing.*;
import java.awt.*;
import Service.*;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import Service.*;
import View.Menu;
import java.security.Provider.Service;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author max
 */
public class panelPercobaan extends javax.swing.JPanel {

    /**
     * Creates new form panelPercobaan
     */
    private CardLayout cl;
    private JPanel panel;
    tampilMobil mobil;
//    String username,JLabel button,JLabel button1,String kode,String brand,String tipe, int harga, ImageIcon foto, JPanel panel,JLabel merk, JLabel tipe1
    public panelPercobaan(String kode,String username,Menu menu, tampilMobil tampil ) {
        tampil.Mobil(kode);
        initComponents();
        favorit.setVisible(false);
        jBrand.setText(tampil.getMerk());
        jTipe.setText(tampil.getTipe());
        String harga3 = CurrencyFormatter.formatToRupiah(tampil.getHarga());
        jHarga.setText("Rp."+harga3+"/Hari");
        jFoto.setIcon(ubahUkuran.resizeImageIcon(tampil.getFotoIcon(), 450));
        tambahFavorit tambahFavorit = new tambahFavorit();
        if(tambahFavorit.validasiFavorit(menu.getUsername(), kode)){
            favorit.setVisible(true);
        }
        status status = new status();
        if (status.status(kode) == 0){
            iconStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconStatusMobil/GreenCircle.png")));
        }else if(status.status(kode)==1){
            iconStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconStatusMobil/RedCircle.png")));
        }else{
            iconStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconStatusMobil/YellowCircle.png")));
        }
        
        
        
        
        lihatMobil.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                CardLayout cl = (CardLayout)panel.getLayout();
//                cl.show(panel, "tampilMobil");
                    tampilMobil1 tampilMobil = new tampilMobil1(kode,username,menu,"daftarMobil",tampil);
                    
                    
                    
                    
            }

            @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
                
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBrand = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        favorit = new javax.swing.JLabel();
        jFoto = new javax.swing.JLabel();
        jTipe = new javax.swing.JLabel();
        iconStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lihatMobil = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 107, 147), 5, true));
        setPreferredSize(new java.awt.Dimension(100, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBrand.setText("TOYOTA");
        add(jBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jHarga.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jHarga.setText("Rp.150.000");
        add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        favorit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bookmark.png"))); // NOI18N
        add(favorit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toyota-all-new-avanza-2015-tangkapan-layar_169-3.jpeg"))); // NOI18N
        add(jFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 550, 230));

        jTipe.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jTipe.setText("avanza");
        add(jTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 280, 64));

        iconStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconStatusMobil/pngwing.com-2.png"))); // NOI18N
        add(iconStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(27, 107, 147));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 75, 96), 3));

        lihatMobil.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lihatMobil.setForeground(new java.awt.Color(255, 255, 255));
        lihatMobil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lihatMobil.setText("Lihat Mobil");
        lihatMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lihatMobilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lihatMobil, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lihatMobil, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void lihatMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatMobilMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_lihatMobilMouseClicked

    public JLabel getLihatMobil() {
        return lihatMobil;
    }

    public void setLihatMobil(JLabel lihatMobil) {
        this.lihatMobil = lihatMobil;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel favorit;
    private javax.swing.JLabel iconStatus;
    private javax.swing.JLabel jBrand;
    private javax.swing.JLabel jFoto;
    private javax.swing.JLabel jHarga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTipe;
    private javax.swing.JLabel lihatMobil;
    // End of variables declaration//GEN-END:variables
    

}
