/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Model_view;

import Service.CurrencyFormatter;
import Service.status;
import Service.tampilMobil;
import Service.ubahUkuran;
import View.Menu;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author max
 */
public class tampilDaftarMobil extends javax.swing.JPanel {

    /**
     * Creates new form tampilPesanan
     */
    public tampilDaftarMobil(String kode,String username,Menu menu, tampilMobil tampil ) {
        initComponents();
        jMerk.setText(tampil.getMerk());
        jTipe.setText(tampil.getTipe());
        String harga3 = CurrencyFormatter.formatToRupiah(tampil.getHarga());
        jHarga.setText("Rp."+harga3+"/Hari");
        jFoto.setIcon(ubahUkuran.resizeImageIcon(tampil.getFotoIcon(), 450));
        lihatMobil.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                CardLayout cl = (CardLayout)panel.getLayout();
//                cl.show(panel, "tampilMobil");
                    System.out.println("ehehe");
                    tampilMobil1 tampilMobil = new tampilMobil1(kode,username,menu,"favorit",tampil);
                    
            }
                @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
                
            }
        });
        
        status status = new status();
        if (status.status(kode) == 0){
            iconStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconStatusMobil/GreenCircle.png")));
        }else if(status.status(kode)==1){
            iconStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconStatusMobil/RedCircle.png")));
        }else{
            iconStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconStatusMobil/YellowCircle.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFoto = new javax.swing.JLabel();
        jTipe = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lihatMobil = new javax.swing.JLabel();
        jMerk = new javax.swing.JLabel();
        iconStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1085, 194));

        jFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toyota-all-new-avanza-2015-tangkapan-layar_169-3.jpeg"))); // NOI18N

        jTipe.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jTipe.setText("AVANZA");

        jHarga.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jHarga.setText("Rp.500.000");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Jumlah seat : 5");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        lihatMobil.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lihatMobil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lihatMobil.setText("SEWA MOBIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lihatMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lihatMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMerk.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMerk.setForeground(new java.awt.Color(102, 102, 102));
        jMerk.setText("TOYOTA");

        iconStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconStatusMobil/GreenCircle.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFoto)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHarga)
                    .addComponent(jLabel4)
                    .addComponent(jTipe)
                    .addComponent(jMerk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jMerk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTipe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jHarga))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconStatus)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconStatus;
    private javax.swing.JLabel jFoto;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMerk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTipe;
    private javax.swing.JLabel lihatMobil;
    // End of variables declaration//GEN-END:variables
}
