/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Model_view;

import Service.CurrencyFormatter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import Service.*;
import java.text.SimpleDateFormat;


/**
 *
 * @author max
 */
public class tampilPesanan4 extends javax.swing.JPanel {

    /**
     * Creates new form tampilPesanan
     */
    private String kPesanan;
    private String kode1;
    public tampilPesanan4(String kode,String status1 ,String status3) {
        initComponents();
        kPesanan = status1;
        kode1 = kode;
        jMerk.setText(kode);
        tampilMobil tampil = new tampilMobil(kode);
        jFoto.setIcon(ubahUkuran.resizeImageIcon(tampil.getFotoIcon(), 450));
        jMerk.setText(tampil.getMerk());
        jTipe.setText(tampil.getTipe());
        status.setText(status3);
        kodePesanan.setText(status1);
        jKode.setText(tampil.getKode());
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        tanggalPesan.setText("Tanggal Pesan      : "+sdf.format(tampil.getTanggalPesan()));
        tanggalBooking.setText("Tanggal Booking    : "+sdf.format(tampil.getTanggalBooking()));
        tanggalKembali.setText("Tanggal Selesai    :"+sdf.format(tampil.getTanggalKembali()));
        if (status.getText().equals("booking")){
            jPanel1.setVisible(true);
            jPanel4.setVisible(false);
        }else if(status.getText().equals("disewa")){
            jPanel1.setVisible(false);
            jPanel4.setVisible(false);
        }
        else{
            jPanel1.setVisible(false);
            jPanel4.setVisible(true);
        }
        if (status.getText().equals("ready")){
            status.setText("selesai");
        }
        
        
//        jTipe.setText(tipe);
//        String harga3 = CurrencyFormatter.formatToRupiah(harga);
//        jHarga.setText("Rp."+harga3+"/Hari");
//        jFoto.setIcon(foto);
//        lihatMobil.addMouseListener(new MouseListener() {
//            @Override
//            public void mouseClicked(MouseEvent e) {
////                CardLayout cl = (CardLayout)panel.getLayout();
////                cl.show(panel, "tampilMobil");
//                  tambahPesanan pesan = new tambahPesanan();
//                  pesan.tambahPesanan(username, kode, lihatMobil);
//                  Menu.pesanan(label2,label3,username);
//                    
//                    
//            }
//                @Override
//            public void mousePressed(MouseEvent e) {
//                
//            }
//
//            @Override
//            public void mouseReleased(MouseEvent e) {
//                
//            }
//
//            @Override
//            public void mouseEntered(MouseEvent e) {
//                
//            }
//
//            @Override
//            public void mouseExited(MouseEvent e) {
//                
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFoto = new javax.swing.JLabel();
        jTipe = new javax.swing.JLabel();
        jMerk = new javax.swing.JLabel();
        jKode = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tanggalPesan = new javax.swing.JLabel();
        tanggalBooking = new javax.swing.JLabel();
        tanggalKembali = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kodePesanan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1085, 194));

        jFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toyota-all-new-avanza-2015-tangkapan-layar_169-3.jpeg"))); // NOI18N

        jTipe.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jTipe.setText("AVANZA");

        jMerk.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMerk.setForeground(new java.awt.Color(102, 102, 102));
        jMerk.setText("TOYOTA");

        jKode.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jKode.setForeground(new java.awt.Color(102, 102, 102));
        jKode.setText("Kode");

        status.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        status.setText("Status");

        jPanel1.setBackground(new java.awt.Color(27, 107, 147));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(67, 91, 102), 5, true));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BATALKAN");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(27, 107, 147));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(67, 91, 102), 5, true));

        tanggalPesan.setForeground(new java.awt.Color(255, 255, 255));
        tanggalPesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggalPesan.setText("jLabel2");

        tanggalBooking.setForeground(new java.awt.Color(255, 255, 255));
        tanggalBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggalBooking.setText("jLabel3");

        tanggalKembali.setForeground(new java.awt.Color(255, 255, 255));
        tanggalKembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggalKembali.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tanggalPesan, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(tanggalBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tanggalKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tanggalPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(79, 192, 208));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 107, 147), 5, true));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELESAI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kodePesanan.setText("Kode Pesanan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jKode)
                    .addComponent(jTipe)
                    .addComponent(jMerk)
                    .addComponent(status)
                    .addComponent(kodePesanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMerk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jKode, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodePesanan)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        batalPesanan batal = new batalPesanan(kode1,kPesanan);
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jFoto;
    private javax.swing.JLabel jKode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jMerk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jTipe;
    private javax.swing.JLabel kodePesanan;
    private javax.swing.JLabel status;
    private javax.swing.JLabel tanggalBooking;
    private javax.swing.JLabel tanggalKembali;
    private javax.swing.JLabel tanggalPesan;
    // End of variables declaration//GEN-END:variables
}
