/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Model_view;

import Service.CurrencyFormatter;
import Service.ubahUkuran;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author max
 */
public class tampilPesanan1 extends javax.swing.JPanel {

    /**
     * Creates new form tampilPesanan
     */
    public tampilPesanan1(String kode,String brand,String tipe, int harga, ImageIcon foto, JPanel panel,JTextField merk, JTextField tipe1, JTextField harga1, JTextArea deskripsi1, JLabel foto1, JTextField kode1) {
        initComponents();
        jMerk.setText(brand);
        jTipe.setText(tipe);
        String harga3 = CurrencyFormatter.formatToRupiah(harga);
        jHarga.setText("Rp."+harga3+"/Hari");
        jFoto.setIcon(ubahUkuran.resizeImageIcon(foto, 450));
        lihatMobil.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                CardLayout cl = (CardLayout)panel.getLayout();
//                cl.show(panel, "tampilMobil");
                    tampilMobil2 tampilMobil = new tampilMobil2(kode,panel, merk, tipe1, harga1, deskripsi1, foto1,kode1);
                    
            }
                @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFoto = new javax.swing.JLabel();
        jTipe = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lihatMobil = new javax.swing.JLabel();
        jMerk = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1085, 194));

        jFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toyota-all-new-avanza-2015-tangkapan-layar_169-3.jpeg"))); // NOI18N

        jTipe.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jTipe.setText("AVANZA");

        jHarga.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jHarga.setText("Rp.500.000");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        lihatMobil.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lihatMobil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lihatMobil.setText("EDIT MOBIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lihatMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lihatMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMerk.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMerk.setForeground(new java.awt.Color(102, 102, 102));
        jMerk.setText("TOYOTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFoto)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTipe)
                        .addComponent(jMerk))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jHarga)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jMerk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTipe)
                .addGap(34, 34, 34)
                .addComponent(jHarga)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jFoto;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jMerk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTipe;
    private javax.swing.JLabel lihatMobil;
    // End of variables declaration//GEN-END:variables
}
