/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Model_view;
import Service.*;
import java.text.SimpleDateFormat;
/**
 *
 * @author max
 */
public class tampilPesananAdmin extends javax.swing.JPanel {

    /**
     * Creates new form tampilPesananAdmin
     */
    public tampilPesananAdmin(String kode) {
        initComponents();
        tampilMobil tampil = new tampilMobil(kode);
        foto.setIcon(ubahUkuran.resizeImageIcon(tampil.getFotoIcon(), 450));
        penyewa.setText(tampil.getPenyewa());
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        tPesan.setText(sdf.format(tampil.getTanggalPesan()));
        tBooking.setText(sdf.format(tampil.getTanggalBooking()));
        tKembali.setText(sdf.format(tampil.getTanggalKembali()));
        status.setText(tampil.getStatus());
        harga.setText("Rp."+CurrencyFormatter.formatToRupiah(tampil.getHargaPesanan())+"/"+String.valueOf(tampil.getHari())+" hari");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foto = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        penyewa = new javax.swing.JLabel();
        tPesan = new javax.swing.JLabel();
        tBooking = new javax.swing.JLabel();
        tKembali = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toyota-all-new-avanza-2015-tangkapan-layar_169-3.jpeg"))); // NOI18N

        status.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        status.setText("Status");

        penyewa.setText("Penyewa");

        tPesan.setText("tanggal pesan");

        tBooking.setText("tanggal booking");

        tKembali.setText("tanggal dikembalikan");

        jLabel1.setText("Penyewa                       :");

        jLabel2.setText("Tanggal Booking          :");

        jLabel3.setText("Tanggal Pesan              :");

        jLabel4.setText("Tanggal Dikembalikan :");

        jLabel5.setText("Harga Pesanan             :");

        harga.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(foto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tKembali)
                            .addComponent(tBooking)
                            .addComponent(penyewa)
                            .addComponent(tPesan)
                            .addComponent(harga))))
                .addGap(0, 499, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(foto)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penyewa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tPesan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tBooking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tKembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(harga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foto;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel penyewa;
    private javax.swing.JLabel status;
    private javax.swing.JLabel tBooking;
    private javax.swing.JLabel tKembali;
    private javax.swing.JLabel tPesan;
    // End of variables declaration//GEN-END:variables
}
