package View;


import Model_view.tampilPesananAdmin;
import Model_view.tampilPesanan1;
import javax.swing.*;
import java.awt.*;
import Service.*;
import config.DatabaseConnector;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author max
 */
public class menuAdmin extends javax.swing.JFrame {

    private JPanel cards = new JPanel(new CardLayout());
    private CardLayout cardLayout;
//    MarketplaceApp panelProduct = new MarketplaceApp();
    private String username;

   
    
    private JPanel panelContainer;
    private JPanel panelContainer1;
    private JPanel panelContainer2;
    private int panelCount = 0;
    private int panelCount1 = 0;
    private int panelCount2 = 0;
    private final int panelWidth = 549;
    private final int panelHeight = 320;
    private String mobilTampil;
    private File selectedFile;
    private File selectedFile2;
    private int pendapatan = 0;

    public String getMobilTampil() {
        return mobilTampil;
    }

    public void setMobilTampil(String mobilTampil) {
        this.mobilTampil = mobilTampil;
    }

    
    
    public menuAdmin(String username1) {
        username = username1;
        
        initComponents();
//        percobaan();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
        dataUser data = new dataUser(username1);
        
        jUsername.setText(data.getUsername());
        jUser.setText(username1);
        
        
        
        panelContainer = new JPanel();
        panelContainer.setLayout(new GridLayout(0, 2, 10, 10)); // Menggunakan GridLayout dengan 2 kolom
        JScrollPane scrollPane = new JScrollPane(panelContainer); // Memasukkan panelContainer ke dalam JScrollPane

        
//        jPanel1.add(scrollPane, BorderLayout.CENTER);
        
        
        panelContainer1 = new JPanel();
        panelContainer1.setLayout(new GridLayout(0, 1, 10, 10)); // Menggunakan GridLayout dengan 2 kolom
        JScrollPane scrollPane1 = new JScrollPane(panelContainer1); // Memasukkan panelContainer ke dalam JScrollPane

        
        panel1Favorit.add(scrollPane1, BorderLayout.CENTER);
        panelContainer2 = new JPanel();
        panelContainer2.setLayout(new GridLayout(0, 1, 10, 10)); // Menggunakan GridLayout dengan 2 kolom
        JScrollPane scrollPane2 = new JScrollPane(panelContainer2); // Memasukkan panelContainer ke dalam JScrollPane
        panel1DaftarPesanan.add(scrollPane2, BorderLayout.CENTER);
        
        

        
        
        

        pack();
        setLocationRelativeTo(null);
        
        
        
        
        
        
//        deskripsi.setEditable(false);
        kode3.setEditable(false);
        
        
        
        
        
        
        
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jBrand = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        jFoto = new javax.swing.JLabel();
        jTipe = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lihatMobil = new javax.swing.JLabel();
        panelNavbar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jUsername = new javax.swing.JLabel();
        profil = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        panelTest = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bFavorit = new javax.swing.JPanel();
        favorit = new javax.swing.JLabel();
        jPesanan = new javax.swing.JPanel();
        tPesanan = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jUser = new javax.swing.JLabel();
        panelFavorit = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        panel1Favorit = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        foto3 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        tipe3 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        kode3 = new javax.swing.JTextField();
        harga3 = new javax.swing.JTextField();
        merk3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        deskripsi3 = new javax.swing.JTextArea();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        foto4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tambahHarga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tambahMerk = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tambahTipe = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tambahDeskripsi = new javax.swing.JTextField();
        tambahKode = new javax.swing.JTextField();
        tambahType = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        panelDaftarPesanan = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        panel1DaftarPesanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tPendapatan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 107, 147), 5, true));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBrand.setText("TOYOTA");
        jPanel13.add(jBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jHarga.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jHarga.setText("Rp.150.000");
        jPanel13.add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toyota-all-new-avanza-2015-tangkapan-layar_169-3.jpeg"))); // NOI18N
        jPanel13.add(jFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 549, 230));

        jTipe.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jTipe.setText("avanza");
        jPanel13.add(jTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 280, 64));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconStatusMobil/pngwing.com-2.png"))); // NOI18N
        jPanel13.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jPanel14.setBackground(new java.awt.Color(162, 255, 134));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 107, 147), 3));

        lihatMobil.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lihatMobil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lihatMobil.setText("Lihat Mobil");
        lihatMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lihatMobilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lihatMobil, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lihatMobil, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 140, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelNavbar.setBackground(new java.awt.Color(45, 67, 86));
        panelNavbar.setPreferredSize(new java.awt.Dimension(922, 80));

        jPanel4.setBackground(new java.awt.Color(45, 67, 86));

        jUsername.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jUsername.setForeground(new java.awt.Color(255, 255, 255));
        jUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jUsername.setText("jLabel7");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(990, Short.MAX_VALUE)
                .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        profil.setForeground(new java.awt.Color(255, 255, 255));
        profil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Car Fire.png"))); // NOI18N

        javax.swing.GroupLayout panelNavbarLayout = new javax.swing.GroupLayout(panelNavbar);
        panelNavbar.setLayout(panelNavbarLayout);
        panelNavbarLayout.setHorizontalGroup(
            panelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profil, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(261, 261, 261)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelNavbarLayout.setVerticalGroup(
            panelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profil)
                .addContainerGap())
        );

        getContentPane().add(panelNavbar, java.awt.BorderLayout.PAGE_START);

        panelMenu.setBackground(new java.awt.Color(67, 91, 102));
        panelMenu.setMinimumSize(new java.awt.Dimension(200, 100));

        panelTest.setBackground(new java.awt.Color(67, 91, 102));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MENU");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTestLayout = new javax.swing.GroupLayout(panelTest);
        panelTest.setLayout(panelTestLayout);
        panelTestLayout.setHorizontalGroup(
            panelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTestLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelTestLayout.setVerticalGroup(
            panelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        bFavorit.setBackground(new java.awt.Color(67, 91, 102));
        bFavorit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bFavoritMouseClicked(evt);
            }
        });

        favorit.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        favorit.setForeground(new java.awt.Color(255, 255, 255));
        favorit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        favorit.setText("Daftar Mobil");
        favorit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favoritMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bFavoritLayout = new javax.swing.GroupLayout(bFavorit);
        bFavorit.setLayout(bFavoritLayout);
        bFavoritLayout.setHorizontalGroup(
            bFavoritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bFavoritLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(favorit, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        bFavoritLayout.setVerticalGroup(
            bFavoritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bFavoritLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(favorit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPesanan.setBackground(new java.awt.Color(67, 91, 102));
        jPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPesananMouseClicked(evt);
            }
        });

        tPesanan.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tPesanan.setForeground(new java.awt.Color(255, 255, 255));
        tPesanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tPesanan.setText("Pesanan");
        tPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPesananMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPesananLayout = new javax.swing.GroupLayout(jPesanan);
        jPesanan.setLayout(jPesananLayout);
        jPesananLayout.setHorizontalGroup(
            jPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPesananLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPesananLayout.setVerticalGroup(
            jPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFavorit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(bFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(657, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(22, 75, 96));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/field_car_18598.png"))); // NOI18N
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 1350, -1));

        jPanel5.setBackground(new java.awt.Color(79, 192, 208));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, -6, 730, 1010));

        jPanel9.setBackground(new java.awt.Color(27, 107, 147));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(79, 192, 208));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 192, 208), 3, true));

        jLabel10.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Lihat Daftar Mobil");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 290, -1));

        jLabel1.setFont(new java.awt.Font("Telugu Sangam MN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DALAM MEMILIH");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 220, 40));

        jLabel3.setFont(new java.awt.Font("Telugu Sangam MN", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UNTUK ANDA");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 220, 40));

        jLabel20.setFont(new java.awt.Font("Telugu Sangam MN", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("MOBIL PILIHAN");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 220, 40));

        jLabel21.setFont(new java.awt.Font("Telugu Sangam MN", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("YANG TERBAIK");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 220, 40));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1040, 830));

        jLabel9.setBackground(new java.awt.Color(67, 91, 102));
        jLabel9.setFont(new java.awt.Font("Telugu MN", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("SELAMAT DATANG");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 60, 600, 70));

        jUser.setBackground(new java.awt.Color(67, 91, 102));
        jUser.setFont(new java.awt.Font("Telugu MN", 1, 48)); // NOI18N
        jUser.setForeground(new java.awt.Color(255, 255, 255));
        jUser.setText("user");
        jUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 240, 60));

        panelContent.add(jPanel7, "menu2");

        panelFavorit.setBackground(new java.awt.Color(255, 255, 255));

        jPanel23.setPreferredSize(new java.awt.Dimension(0, 800));
        jPanel23.setLayout(new java.awt.CardLayout());

        panel1Favorit.setLayout(new java.awt.BorderLayout());
        jPanel23.add(panel1Favorit, "listFavorit");

        jPanel22.setMaximumSize(new java.awt.Dimension(2236, 1084));
        jPanel22.setPreferredSize(new java.awt.Dimension(2236, 1084));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBackground(new java.awt.Color(27, 107, 147));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(79, 192, 208));
        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 75, 96), 5));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("SIMPAN EDIT DATA");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel33.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 300, 70));

        jPanel39.setBackground(new java.awt.Color(79, 192, 208));
        jPanel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 75, 96), 5));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("HAPUS DATA");
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel33.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 310, -1));

        jPanel22.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(-590, 662, 2900, 140));

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setPreferredSize(new java.awt.Dimension(2236, 1084));

        foto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toyota-all-new-avanza-2015-tangkapan-layar_169-3.jpeg"))); // NOI18N
        foto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foto3MouseClicked(evt);
            }
        });

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        tipe3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe3ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("KODE MOBIL :");

        kode3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode3ActionPerformed(evt);
            }
        });

        harga3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        harga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga3ActionPerformed(evt);
            }
        });

        merk3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        merk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merk3ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("MERK MOBIL :");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setText("TIPE MOBIL :");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setText("HARGA MOBIL :");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setText("DESKRIPSI MOBIL :");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("EDIT DATA MOBIL");

        deskripsi3.setColumns(20);
        deskripsi3.setRows(5);
        jScrollPane4.setViewportView(deskripsi3);

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kode3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foto3)
                        .addComponent(jLabel39)))
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addComponent(merk3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41)
                            .addComponent(harga3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43)
                            .addGroup(jPanel35Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(232, 232, 232)
                                .addComponent(tipe3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(2088, 2088, 2088)
                        .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel44)))
                .addGap(20, 20, 20)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addComponent(foto3)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addComponent(kode3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(574, 574, 574))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(merk3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18)
                        .addComponent(tipe3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(harga3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(553, 553, 553))))
        );

        jPanel22.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 27, 1030, 1070));

        jPanel37.setBackground(new java.awt.Color(79, 192, 208));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel38.setBackground(new java.awt.Color(27, 107, 147));
        jPanel38.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 75, 96), 5, true));

        jLabel45.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Back");
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel38Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel37.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, 50));

        jPanel22.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, -60, 1240, 1170));

        jPanel23.add(jPanel22, "tampilMobil1");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMaximumSize(new java.awt.Dimension(2266, 1084));
        jPanel8.setPreferredSize(new java.awt.Dimension(2236, 1084));

        jPanel11.setBackground(new java.awt.Color(79, 192, 208));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setMaximumSize(new java.awt.Dimension(2266, 1084));
        jPanel12.setMinimumSize(new java.awt.Dimension(2266, 1084));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel40.setBackground(new java.awt.Color(27, 107, 147));
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel41.setBackground(new java.awt.Color(79, 192, 208));
        jPanel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 75, 96), 5));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TAMBAH MOBIL");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel41Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel41Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel40.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 240, 70));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TAMBAH DATA MOBIL");

        foto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toyota-all-new-avanza-2015-tangkapan-layar_169-3.jpeg"))); // NOI18N
        foto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foto4MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("MERK MOBIL :");

        tambahHarga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambahHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahHargaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("TIPE MOBIL :");

        tambahMerk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambahMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMerkActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("HARGA MOBIL :");

        tambahTipe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambahTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTipeActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("DESKRIPSI MOBIL :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("KODE MOBIL :");

        tambahDeskripsi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambahDeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDeskripsiActionPerformed(evt);
            }
        });

        tambahKode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambahKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKodeActionPerformed(evt);
            }
        });

        tambahType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambahType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTypeActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("TYPE MOBIL :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, 2194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foto4)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(tambahKode, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(tambahType, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(tambahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(tambahMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(tambahTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(tambahDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(1324, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(foto4)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(tambahKode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tambahType, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(tambahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel15))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tambahMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tambahTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tambahDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(924, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel23.add(jPanel8, "tambahMobil");

        jPanel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TAMBAH MOBIL");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("UBAH MOBIL");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFavoritLayout = new javax.swing.GroupLayout(panelFavorit);
        panelFavorit.setLayout(panelFavoritLayout);
        panelFavoritLayout.setHorizontalGroup(
            panelFavoritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 1426, Short.MAX_VALUE)
            .addGroup(panelFavoritLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFavoritLayout.setVerticalGroup(
            panelFavoritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFavoritLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelFavoritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 806, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContent.add(panelFavorit, "favorit");

        jPanel28.setBackground(new java.awt.Color(255, 0, 0));
        jPanel28.setLayout(new java.awt.CardLayout());

        panel1DaftarPesanan.setLayout(new java.awt.BorderLayout());
        jPanel28.add(panel1DaftarPesanan, "listFavorit");

        tPendapatan.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        tPendapatan.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Pendapatan:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(786, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelDaftarPesananLayout = new javax.swing.GroupLayout(panelDaftarPesanan);
        panelDaftarPesanan.setLayout(panelDaftarPesananLayout);
        panelDaftarPesananLayout.setHorizontalGroup(
            panelDaftarPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarPesananLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelDaftarPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDaftarPesananLayout.setVerticalGroup(
            panelDaftarPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarPesananLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContent.add(panelDaftarPesanan, "daftarPesanan");

        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1656, 1007));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        
        openMenu(panelTest,jPesanan,jLabel4,tPesanan);
        
        openMenu(panelTest,bFavorit,jLabel4,favorit);
        CardLayout cl = (CardLayout)panelContent.getLayout();
        cl.show(panelContent, "menu2");
        
        

    }//GEN-LAST:event_jLabel4MouseClicked

    public JPanel getjPanel13() {
        return jPanel13;
    }

    public void setjPanel13(JPanel jPanel13) {
        this.jPanel13 = jPanel13;
    }
    
    
    private void favoritMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoritMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)panelContent.getLayout();
        cl.show(panelContent, "favorit");
        addSmallPanel1();
        openMenu(bFavorit,panelTest,favorit,jLabel4);
        openMenu(bFavorit,jPesanan,favorit,tPesanan);
        
        
        
    }//GEN-LAST:event_favoritMouseClicked
    private void tampilMobilMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)panelContent.getLayout();
        cl.show(panelContent, "tampilMobil");
        System.out.println("ehe");
        
    } 
    private void bFavoritMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFavoritMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bFavoritMouseClicked

    private void tPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPesananMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)panelContent.getLayout();
        cl.show(panelContent, "daftarPesanan");
        CardLayout cl1 = (CardLayout)jPanel28.getLayout();
        cl1.show(jPanel28, "listFvorit");
        openMenu(jPesanan,panelTest,tPesanan,jLabel4);
        
        addSmallPanel2();
        openMenu(jPesanan,bFavorit,tPesanan,favorit);
        
        
        
    }//GEN-LAST:event_tPesananMouseClicked

    private void jPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPesananMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPesananMouseClicked

    private void lihatMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatMobilMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lihatMobilMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
//        CardLayout cl = (CardLayout)panelContent.getLayout();
//        cl.show(panelContent, "daftarMobil");
//        
//       
        CardLayout cl = (CardLayout)panelContent.getLayout();
        cl.show(panelContent, "daftarMobil");
        
       
        
        
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)jPanel23.getLayout();
        cl.show(jPanel23, "listFavorit");

    }//GEN-LAST:event_jLabel45MouseClicked

    private void merk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merk3ActionPerformed

    private void harga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga3ActionPerformed

    private void kode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode3ActionPerformed

    private void tipe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipe3ActionPerformed

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:

        String query = "UPDATE daftarMobil SET merk = ? , tipe = ?, harga = ? , deskripsi = ?  WHERE kode = ?";
        try (Connection conn = DatabaseConnector.getConnection();
            PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, merk3.getText());
            stmt.setString(2, tipe3.getText());
            stmt.setInt(3, Integer.valueOf(harga3.getText()));
            stmt.setString(4, deskripsi3.getText());
            stmt.setString(5, kode3.getText());
            uploadGambar.uploadImage(selectedFile, kode3.getText());
            JOptionPane.showMessageDialog(null, "UPDATE DATA BERHASIL","Pesan",JOptionPane.INFORMATION_MESSAGE);
            stmt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void foto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foto3MouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
                int result = fileChooser.showOpenDialog(this);
                if (result == JFileChooser.APPROVE_OPTION) {
                    selectedFile = fileChooser.getSelectedFile();
                    foto3.setIcon(uploadGambar.createImageIcon(selectedFile.getPath()));
                    
                }           
        
    }//GEN-LAST:event_foto3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)jPanel23.getLayout();
        cl.show(jPanel23, "tambahMobil");

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)jPanel23.getLayout();
        cl.show(jPanel23, "listFavorit");
    }//GEN-LAST:event_jLabel17MouseClicked

    private void tambahHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahHargaActionPerformed

    private void tambahMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahMerkActionPerformed

    private void tambahTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahTipeActionPerformed

    private void tambahDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahDeskripsiActionPerformed

    private void tambahKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahKodeActionPerformed

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
        String query = "DELETE FROM daftarMobil WHERE kode = ?";
        try (Connection conn = DatabaseConnector.getConnection();
            PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, kode3.getText());
            JOptionPane.showMessageDialog(null, "DELETE DATA BERHASIL","Pesan",JOptionPane.INFORMATION_MESSAGE);
            stmt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        tambahMobil tambah = new tambahMobil();
        try {
            tambah.tambah(tambahKode.getText(), tambahMerk.getText(), tambahTipe.getText(), Integer.valueOf(tambahHarga.getText()), tambahDeskripsi.getText(), selectedFile2, tambahType.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(menuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void foto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foto4MouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
                int result = fileChooser.showOpenDialog(this);
                if (result == JFileChooser.APPROVE_OPTION) {
                    selectedFile2 = fileChooser.getSelectedFile();
                    foto4.setIcon(uploadGambar.createImageIcon(selectedFile2.getPath()));
                    
                }  
    }//GEN-LAST:event_foto4MouseClicked

    private void tambahTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahTypeActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bFavorit;
    private javax.swing.JTextArea deskripsi3;
    private javax.swing.JLabel favorit;
    private javax.swing.JLabel foto3;
    private javax.swing.JLabel foto4;
    private javax.swing.JTextField harga3;
    private javax.swing.JLabel jBrand;
    private javax.swing.JLabel jFoto;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPesanan;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jTipe;
    private javax.swing.JLabel jUser;
    private javax.swing.JLabel jUsername;
    private javax.swing.JTextField kode3;
    private javax.swing.JLabel lihatMobil;
    private javax.swing.JTextField merk3;
    private javax.swing.JPanel panel1DaftarPesanan;
    private javax.swing.JPanel panel1Favorit;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelDaftarPesanan;
    private javax.swing.JPanel panelFavorit;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNavbar;
    private javax.swing.JPanel panelTest;
    private javax.swing.JLabel profil;
    private javax.swing.JLabel tPendapatan;
    private javax.swing.JLabel tPesanan;
    private javax.swing.JTextField tambahDeskripsi;
    private javax.swing.JTextField tambahHarga;
    private javax.swing.JTextField tambahKode;
    private javax.swing.JTextField tambahMerk;
    private javax.swing.JTextField tambahTipe;
    private javax.swing.JTextField tambahType;
    private javax.swing.JTextField tipe3;
    // End of variables declaration//GEN-END:variables
//    void percobaan(){
//        JPanel panel = panelProduct.mainPanel();
//        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
//                menu1.setLayout(menu1Layout);
//                menu1Layout.setHorizontalGroup(
//                    menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(menu1Layout.createSequentialGroup()
//                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(0, 300, Short.MAX_VALUE))
//                );
//                menu1Layout.setVerticalGroup(
//                    menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(menu1Layout.createSequentialGroup()
//                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(0, 200, Short.MAX_VALUE))
//                );
////        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
////        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
//       
//    }
    void openMenu(JPanel panel1, JPanel panel2, JLabel label1, JLabel label2){
        panel1.setBackground(Color.white);
        label1.setForeground(Color.black);
        panel2.setBackground(new java.awt.Color(67, 91, 102));
        label2.setForeground(Color.white);
    }
   
    
    
    private void addSmallPanel1() {
        panelContainer1.removeAll();

        //IMPORTANT
        panelContainer1.revalidate();
        panelContainer1.repaint();
       
        try {
            Connection connection = DatabaseConnector.getConnection();
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM daftarMobil";
            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                String kode2 = resultSet.getString("kode");
                String tipe2 = resultSet.getString("tipe");
                String merk2 = resultSet.getString("merk");
                
                int harga2 = resultSet.getInt("harga");
                String deskripsi2 = resultSet.getString("deskripsi");
                byte[] fotoBytes = resultSet.getBytes("foto");
                ImageIcon fotoIcon = new ImageIcon(fotoBytes);
                
                
                // Create panel for each product
                
                JPanel smallPanel = new tampilPesanan1(kode2,merk2,tipe2,harga2,fotoIcon,jPanel23,merk3,tipe3,harga3,deskripsi3,foto3,kode3);
//                jBrand.setText(merk);
//                jTipe.setText(tipe);
//                jHarga.setText(String.valueOf(harga));
//                jFoto.setIcon(fotoIcon);
//                JPanel smallPanel =  jPanel13;
//                JPanel smallPanel =  getjPanel13();
        
                


                panelContainer1.add(smallPanel);
                panelCount1++;

                revalidate();
                repaint();

            }

            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error connecting to the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private void addSmallPanel2() {
        panelContainer2.removeAll();

        //IMPORTANT
        panelContainer2.revalidate();
        panelContainer2.repaint();
       
        try {
            Connection connection = DatabaseConnector.getConnection();
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM pesanan WHERE 1";
            ResultSet resultSet = statement.executeQuery(query);
            pendapatan = 0;
            while (resultSet.next()) {
                String kode2 = resultSet.getString("mobil");
                String status = resultSet.getString("status");
                if (status.equals("selesai")){
                pendapatan = pendapatan + resultSet.getInt("harga");
                tPendapatan.setText("Rp."+CurrencyFormatter.formatToRupiah(pendapatan));
                
                }
                
                // Create panel for each product
                
                JPanel smallPanel = new tampilPesananAdmin(kode2);
//                jBrand.setText(merk);
//                jTipe.setText(tipe);
//                jHarga.setText(String.valueOf(harga));
//                jFoto.setIcon(fotoIcon);
//                JPanel smallPanel =  jPanel13;
//                JPanel smallPanel =  getjPanel13();
        
                


                panelContainer2.add(smallPanel);
                panelCount2++;

                revalidate();
                repaint();

            }

            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error connecting to the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    
        
    
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menuAdmin("ardi").setVisible(true);
            }
        });
    }
    

}
